homepage: "https://github.com/WasmEdge/WasmEdge"
language: c++
primary_contact: "soroushsaririan"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
  - undefined
main_repo: 'https://github.com/soroushsaririan/WasmEdge-mac.git'
